#!/bin/sh
#
# @name Aion Robotics R1 Rover
# @type Rover
# @class Rover

# ---------- upstream settings: --------
#. ${R}etc/init.d/rc.rover_differential_defaults

#param set-default PWM_MAIN_FUNC1 101
#param set-default PWM_MAIN_FUNC2 101
#param set-default PWM_MAIN_FUNC6 102
#param set-default PWM_MAIN_FUNC7 102

# ---------- my settings: --------
#
# only used in SITL mode with Gazebo
# For Rpi hardware mode see .../PX4-Autopilot/ROMFS/px4fmu_common/init.d/airframes/50005_lawnMower1_config
#

export MYSCRIPTNAME="`pwd`/.../1061_r1_rover"
echo "----------------------------"
echo "IP: starting " $MYSCRIPTNAME

echo "IP: calling ${R}etc/init.d/rc.rover_differential_defaults"
. ${R}etc/init.d/rc.rover_differential_defaults
#. ${R}etc/init.d/rc.rover_defaults
param set CA_AIRFRAME 6
param set CA_R_REV 3

# rc.rover_differential_defaults sets the following:
# Control Allocation (a.k.a. Mixers) for wheels:
#param set CA_AIRFRAME 6
# mark motors as bi-directional here for each channel (bitmask):
#param set CA_R_REV 3

#param set EKF2_MAG_TYPE 0

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1
# We can drive in manual mode when GPS check fails:
param set-default COM_ARM_WO_GPS 1

echo "OK: returned from ${R}etc/init.d/rc.rover_differential_defaults"

# adjust all parameters to ensure smooth driving:
#param set GND_L1_PERIOD 0
#param set GND_MAN_USE_PID 0

#param set GND_HEADING_D 0
#param set GND_HEADING_I 0.2
#param set GND_HEADING_IMAX 0.6
#param set GND_HEADING_P 0.5

#param set GND_TURNRATE_D 0.01
#param set GND_TURNRATE_I 0.3
#param set GND_TURNRATE_IMX 0.3
#param set GND_TURNRATE_P 0.5
#param set GND_YAWL_EF_MAX 1
#param set GND_YAWR_EF_MAX 1

#param set GND_SPEED_D 0
#param set GND_SPEED_I 0.7
#param set GND_SPEED_IMAX 0.3
#param set GND_SPEED_P 0.5
#param set GND_SPEED_TRIM 1.8

#param set GND_SPD_ARR_MIN 0.1
#param set GND_SPD_DEP_MIN 0.1
#param set GND_EMA_PERIOD 10
#param set GND_DECEL_DIST 2
#param set GND_ACCEL_DIST 2

#param set GND_TURN_PRECISN 15
#param set GND_WP_PRECISN 0.7
#param set GND_STOP_PRECISN 0.05

# Enable debug data logging:
# Data logging to "SD card" (~/px4wrk/log):
# "0" = armed to disarmed
param set SDLOG_MODE 0
# Bit 5 - Debug. 123 = 0b01111011  163 = 0b10100011
param set SDLOG_PROFILE 32

param set-default MIS_TAKEOFF_ALT 0.01
#param set-default NAV_ACC_RAD 0.5
param set NAV_ACC_RAD 0.3000
param set-default NAV_LOITER_RAD 2

# Rovers don't have airspeed sensors:
#param set SYS_HAS_NUM_ASPD 0

# Simulated GPS works at fix level 3:
param set GND_GPS_MINFIX 3

# Set Differential Drive Kinematics Library parameters:
param set RDD_WHEEL_BASE 0.58
param set RDD_WHEEL_RADIUS 0.22
param set RDD_WHEEL_SPEED 10.0	# Maximum wheel speed rad/s

# Lawnmower parameters to scale Differential Drive Kinematics output:
param set-default RDD_THRUST_SC 2.5
param set-default RDD_TORQUE_SC 10.0

# set SITL PWM_MAIN output parameters:

# "Motors" - PCA9685 servo channels 1 (Right) and 2 (Left) -
# mixing INDEX_YAW and INDEX_THROTTLE (vehicle_torque_setpoint and vehicle_thrust_setpoint) to "Motor 1" and "Motor 2":

param set PWM_MAIN_FUNC1 201  # right wheel
param set PWM_MAIN_FUNC2 202  # left wheel

# Cutter deck blades clutch, PCA9685 servo channel 3,  "RC FLAPS" (406) - leftmost switch, or "Servo 3" (203):
param set PWM_MAIN_FUNC3 203

# Gas engine throttle, PCA9685 servo channel 4, "RC AUX1" (407) - left knob, or "Servo 4" (204):
#    - on minimum when disarmed or failed:
param set PWM_MAIN_FUNC4 204

# Controlling PCA9685 servos 5,6,7,8 directly via "Servo 5..8" setting, by publishing actuator_servos.control[]:

# Strobes, PCA9685 servo channel 5, "Servo 5" (205) - flashing indicates Mission mode:
param set PWM_MAIN_FUNC5 205

# Horn, PCA9685 servo channel 6, "Servo 6" (206) - for alarms like GPS failure:
param set PWM_MAIN_FUNC6 206

# Spare PCA9685 servo channel 7 on "RC AUX2" (408) - right knob, or "Servo 7" (207):
param set PWM_MAIN_FUNC7 207

# Spare PCA9685 servo channel 8 - "Servo 8" (208):
param set PWM_MAIN_FUNC8 208

echo "OK: finished " $MYSCRIPTNAME
echo "----------------------------"
export MYSCRIPTNAME="`pwd`/.../1061_r1_rover.post"
echo "----------------------------"
echo "IP: starting " $MYSCRIPTNAME


echo "OK: finished " $MYSCRIPTNAME
echo "----------------------------"
