#!/bin/sh
#
# @name Zero Turn Lawn Mower
#
# @url https://photos.app.goo.gl/jwYZRtTi1LVshQoW8
#
# @type Rover
# @class Rover
#
# @maintainer Sergei Grichine
#

export MYSCRIPTNAME="`pwd`/.../50005_lawnMower1_config"

echo "====================================="
echo "IP: starting " $MYSCRIPTNAME
echo "FYI: work dir: `pwd`     running at nice=`nice`"
echo "FYI: AUTOCNF=" $AUTOCNF

# Must have robot name (i.e. DRAGGER) in that file:
set PX4_ROBOT_NAME $(cat /home/pi/PX4_ROBOT_NAME.txt)
echo "FYI: PX4_ROBOT_NAME=" $PX4_ROBOT_NAME

echo "IP: calling ${R}etc/init.d/rc.rover_lawnmower_defaults"
. ${R}etc/init.d/rc.rover_lawnmower_defaults
echo "OK: returned from ${R}etc/init.d/rc.rover_lawnmower_defaults"

echo "FYI: param SYS_AUTOSTART: " `param show -q SYS_AUTOSTART`

# Note: the "set-default" does not save values in "parameters" file, and does not mark them "changed".
#       thus they become session parameters, not persisting between runs. Avoid using set-default overall.

echo "IP: AUTOCNF = yes  - setting all platform default parameters"

# LiFePO4 13.46V battery:
param set-default BAT1_A_PER_V 15.3910
param set-default BAT1_N_CELLS 4
param set-default BAT1_V_CHARGED 3.3650
param set-default BAT1_V_EMPTY 3.2125
param set-default BAT1_V_DIV 4.6730

# Disable Airspeed check circuit breaker because Rovers don't have airspeed sensor:
param set-default CBRK_SUPPLY_CHK 894281
#param set-default CBRK_VELPOSERR 201607
#param set-default CBRK_IO_SAFETY 0

# Commander parameters - defaults for safe operation:
param set-default COM_CPU_MAX -1.0
param set-default COM_RC_IN_MODE 0
param set-default COM_POS_FS_EPH 20
param set-default COM_POS_LOW_EPH -1.0

# Default 7, i.e. use geo lookup and save on disarm
# Option: preset mag declination, no geo lookup, do not use declination in 3D mode (see .post file at the end):
param set-default EKF2_DECL_TYPE 0
param set-default EKF2_MAG_DECL 4

# Option 0: No IMU or Magnetometer
#param set-default EKF2_MULTI_IMU 0
#param set-default EKF2_MULTI_MAG 0

# Option 1: we have one IMU without mag on mpu9250, and separate mag on RM3100 (best used):
# Option 2: we have one IMU with mag on mpu9250 with -M:
#param set-default EKF2_MULTI_IMU 1
#param set-default EKF2_MULTI_MAG 1

# Option 3: we have one IMU with mag (mpu9250 -M) and second mag (RM3100) and 6-axis BMI088 IMU:
#           this configuration quickly loses orientation, do not use without testing.
#           *_MODE=0 allows publishing all Mag and IMU data, not only Primary's
#           We will have 4 instances of EKF2 here ("ekf2 status")
param set-default SENS_IMU_MODE 0
param set-default SENS_MAG_MODE 0
param set-default EKF2_MULTI_IMU 2
param set-default EKF2_MULTI_MAG 2

# Rovers don't have airspeed sensors:
#param set-default SYS_HAS_NUM_ASPD 0

# Data logging to "SD card" (/fs/microsd/log):
# "0" = armed to disarmed
param set-default SDLOG_MODE 0

# Bitmask SDLOG_PROFILE:
# 0: Default set (general log analysis)
# 1: Estimator replay (EKF2)
# 2: Thermal calibration
# 3: System identification
# 4: High rate
# 5: Debug
# 6: Sensor comparison
# 7: Computer Vision and Avoidance
# 8: Raw FIFO high-rate IMU (Gyro)
# 9: Raw FIFO high-rate IMU (Accel)
# 10: Mavlink tunnel message logging

# 123 = 0b01111011
# 131 = 0b10000011
# 163 = 0b10100011

#param set-default SDLOG_PROFILE 255
param set-default SDLOG_PROFILE 123

# ====================================================================================
# Differential Parameters
# See https://docs.px4.io/main/en/config_rover/differential.html

# ====================================================================================

echo "IP: configuring parameters for " $PX4_ROBOT_NAME

# Adjust to fit actual battery voltage:
param set-default BAT1_V_DIV 4.5380

# Set Differential Drive Kinematics Library parameters:
param set-default RD_WHEEL_TRACK 0.58

# Lawnmower "monitoring State Machine" specific parameters:
param set-default LM_ACCEL_DIST 1.0
param set-default LM_DECEL_DIST 1.0
param set-default LM_GPS_MINFIX 6
param set-default LM_TRACING_LEV 5
param set-default LM_STATS_DIST 1.5

# Internal Combustion Engine parameters in different phases of operation:
param set-default LM_ICE_ARRIVE 0.8
param set-default LM_ICE_DEPART 0.8
param set-default LM_ICE_IDLE 0
param set-default LM_ICE_STRAIGHT 1.0
param set-default LM_ICE_TURN 0.2

# Turn accuracy parameters - heading errors to transition from DRIVE to TURN:
#param set-default RD_TRANS_DRV_TRN 0.349066
param set-default RD_TRANS_DRV_TRN 0.785398

param set-default RD_TRANS_TRN_DRV 0.087266
#param set-default RD_TRANS_TRN_DRV 0.174533

# Navigation planning parameters:
param set-default NAV_ACC_RAD 0.2
param set-default RD_ACC_RAD_MARGN 0.2

# Pure / Stanley pursuit parameters:
param set-default PP_LOOKAHD_GAIN 4
param set-default PP_LOOKAHD_MAX 1.51
param set-default PP_LOOKAHD_MIN 1.5

# Grassroamer max speed is 1.1 m/s as measured on R/C, speed setpoint is set a bit lower:
param set-default RO_MAX_THR_SPEED 1.1
param set-default RO_SPEED_LIM 0.9

param set-default RO_ACCEL_LIM 0.05
param set-default RO_DECEL_LIM 0.05
param set-default RO_JERK_LIM 1

# Rover Velocity Control Parameters
param set-default RO_SPEED_I 0.01
param set-default RO_SPEED_P 0.1
param set-default RO_SPEED_RED 1.0
param set-default RO_SPEED_TH 0.1

# Rover Turn Rate Control Parameters
param set-default RO_YAW_ACCEL_LIM 400
param set-default RO_YAW_DECEL_LIM 800
param set-default RO_YAW_RATE_CORR 1.0
param set-default RO_YAW_RATE_TH 0.0

# Rover Attitude (Turn) Control Parameters:
param set-default RO_YAW_P 1.0
param set-default RO_YAW_RATE_I 0.3
param set-default RO_YAW_RATE_P 0.4
param set-default RO_YAW_RATE_LIM 40

# Rover R/C Stick feel adjustments and dead zone for turns:
param set-default RO_YAW_STICK_DZ 0.05
param set-default RD_YAW_STK_GAIN 0.5
param set-default RO_YAW_EXPO 0.0
param set-default RO_YAW_SUPEXPO 0.5

# AHRS must have baro input, unless this is set to 0:
param set-default SYS_HAS_BARO 0
param set-default EKF2_BARO_CTRL 0

# Option 2: we have one IMU with mag on mpu9250 with -M:
param set-default EKF2_MULTI_IMU 1
param set-default EKF2_MULTI_MAG 1

# only consider heading from magnetometer (1) or use all three axes (2):
#	0: Automatic (heading on ground, 3D in-flight)
#	1: Magnetic heading (2D)
#	2: 3-axis (3D)
#	5: none (i.e. use GPS instead, disable/ignore magnetometer)
#	6: use mag for initialization only
param set-default EKF2_MAG_TYPE 5

# have EKF2 estimator use BARO (0) or GPS (1) for altitude.
param set-default EKF2_HGT_REF 1

# To disable GPS Altitute fusing set this to 5 (default 7). For dual RTK GPS heading set it to 15:
param set-default EKF2_GPS_CTRL 15
param set-default EKF2_REQ_FIX 5

# ======================== GPS Hardware ====================================
# see src/drivers/gps/params.yaml
#     docs/en/advanced_config/parameter_reference.md
#     https://docs.px4.io/main/en/advanced_config/parameter_reference#gps
#
# GPS_DUMP_COMM:     Log GPS communication data (default 0)
# GPS_UBX_DYNMODEL:  u-blox GPS dynamic platform model (4 - Automotive)
# GPS_UBX_DGNSS_TO:  u-blox GPS DGNSS timeout (default 0 - use u-blox default timeout)
# GPS_UBX_MIN_CNO:   u-blox GPS minimum satellite signal level for navigation. Default 0 (use u-blox default)
# GPS_UBX_MIN_ELEV:  u-blox GPS minimum satellite elevation angle. Default 0 (use u-blox default)
# GPS_UBX_RATE:      output rate of u-blox GPS receivers (protocol v27+) F9P can in theory do up to 20Hz, realistically 5-7Hz. Default 0 (5Hz for F9P).
# GPS_SAT_INFO:      Enable publication of satellite info (ORB_ID(satellite_info)) if possible (default 0, disabled)
# GPS_UBX_MODE:      1: Heading (Rover with Moving Base UART1 connected to Autopilot, UART2 connected to Moving Base)
# GPS_UBX_BAUD2:     baudrate for the F9P's UART2 port (RTCM corrections)
# GPS_UBX_CFG_INTF:  I2C u-blox protocol configuration (default 0)
# GPS_UBX_PPK:       Post-processed Kinematics (PPK) - default: 0
# GPS_UBX_JAM_DET:   default: 1
# GPS_CFG_WIPE:      Wipes the flash config of UBX modules (default 0)
# GPS_YAW_OFFSET:    Heading/Yaw offset for dual antenna GPS.
# GPS_1_PROTOCOL:    1=UBX  6-=NMEA  0=auto-detect
# GPS_2_PROTOCOL:
# GPS_1_GNSS:        bitmask for GNSS constellations
# GPS_2_GNSS:

# set GPS protocol to UBX (1, default) NMEA (6) or auto-detect (0):
param set-default GPS_1_PROTOCOL 1
param set-default GPS_2_PROTOCOL 1
# wipe GPS FLASH config, if any, to ensure it is in a known state:
param set-default GPS_CFG_WIPE 1

# Automotive model:
param set-default GPS_UBX_DYNMODEL 4

# if left default=0, will be 5 Hz
#param set-default GPS_UBX_RATE 8

# Disable all but GNSS constellations (Glonass, Galileo...) for faster rate (not very stable RTK fix):
#param set-default GPS_1_GNSS 1
#param set-default GPS_2_GNSS 1
# Use GPS, SBAS and Glonass for both receivers (good 9Hz):
param set-default GPS_1_GNSS 19
param set-default GPS_2_GNSS 19
# Use GPS, SBAS, BeiDou and Glonass (slow):
#param set-default GPS_1_GNSS 27
#param set-default GPS_2_GNSS 27
# Use all:
#param set-default GPS_1_GNSS 0
#param set-default GPS_2_GNSS 0

# Secondary GPS (Moving Base) is connected to telemetry radio for RTCM feed, the radio baud rate is 57600.
# This also affects UART2 on the Rover GPS, but this is OK.
param set-default GPS_UBX_MODE 1
param set-default GPS_UBX_BAUD2 57600

# For dual RTK GPS heading:
#    - 0 when Moving Base antenna is behind the main Rover GPS antenna,
#    - 180 when Moving Base antenna is in front of the Rover GPS antenna:
param set-default GPS_YAW_OFFSET 0

# ======================================================================

# Disable GPS blending, always use Main GPS:
param set-default SENS_GPS_MASK 0
param set-default SENS_GPS_PRIME 0

# For dual RTK GPS set position, heading and velocity noise low:
param set-default EKF2_GPS_P_NOISE 0.05
param set-default EKF2_GPS_V_NOISE 0.1
#param set-default EKF2_HEAD_NOISE 0.01 - this goes to mag fusing, not GPS

# Adjust other GPS related parameters for better EKF2 operation:
#param set-default EKF2_GPS_DELAY 110
param set-default SENS_GPS0_OFFX 0.0
param set-default SENS_GPS0_OFFY 0.0
param set-default SENS_GPS0_OFFZ 0.5
#param set-default EKF2_TAU_POS 0.25

# We can drive in manual mode when GPS check fails:
param set-default COM_ARM_WO_GPS 1

# IMU bias bits, to inhibit publishing biases: 0-Gyro, 1-Accel, 2-Gravity vector fusion. Default 3 (Gyro and Accel bias publishing inhibited).
#param set-default EKF2_IMU_CTRL 3
param set-default EKF2_IMU_CTRL 7
# Disable External Vision, Rangers:
param set-default EKF2_EV_CTRL 0
param set-default EKF2_RNG_CTRL 0
# Relax drift requirements on checkup and Accel/Gyro Bias limits:
param set-default EKF2_REQ_HDRIFT 1.0
param set-default EKF2_REQ_VDRIFT 1.0
param set-default EKF2_ABL_LIM 1.0
param set-default EKF2_ABL_GYRLIM 1.0
# Disable obscure EKF2 features, like compensating for centripetal acceleration during turns
#    and IMU delta velocity bias estimation:
param set-default EKF2_GSF_TAS 0
param set-default EKF2_MAG_CHECK 0
param set-default EKF2_GPS_CHECK 0
# wait for 5 seconds to declare GPS healthy:
param set-default EKF2_REQ_GPS_H 5.0

# Disable auto-calibration of Gyro and Accel and related functions:
param set-default SENS_IMU_AUTOCAL 0
param set-default SENS_MAG_AUTOCAL 0
param set-default IMU_GYRO_CAL_EN 0
param set-default MBE_ENABLE 0
param set-default MC_AT_EN 0

# Default 15Hz is too limiting for magnetometer updates:
#param set-default SENS_MAG_RATE 100

# This is mpu9250 compass orientation, x - left, y - backwards:
param set-default SENS_BOARD_ROT 0
param set-default SENS_BOARD_Z_OFF 0

# Disable mag inconsistency preflight check on arming:
param set-default COM_ARM_MAG_ANG 90
param set-default COM_ARM_MAG_STR 2

# Set some device parameters:
param set-default IMU_GYRO_RATEMAX 800
param set-default IMU_INTEG_RATE 250
#param set-default LND_FLIGHT_T_HI 63
param set-default LND_FLIGHT_T_LO 1916514503

# Control Allocation (a.k.a. Mixers) for wheels:
param set-default CA_AIRFRAME 6
# mark motors as bi-directional here for each channel (bitmask):
param set-default CA_R_REV 3

# ===================== set PWM output parameters: =============================

param set-default PCA9685_EN_BUS 1
param set-default PCA9685_I2C_ADDR 64

# Bitmask to reverse PWM output direction, bit 0 - channel 1, bit 1 - channel 2, etc.:
#param set-default PCA9685_REV 0
# how often to send update events via I2C. Default 50Hz, can be increased to 100Hz for better response, but may cause I2C overload:
#param set-default PCA9685_SCHD_HZ 50

# "Motors" - PCA9685 servo channels 1 (Right) and 2 (Left)
# Option with CA: mixing INDEX_YAW and INDEX_THROTTLE (vehicle_torque_setpoint and vehicle_thrust_setpoint) to "Motor 1" and "Motor 2":

param set-default PCA9685_FUNC1 102	# 202 - avoiding Control Allocator (Servo 2), 102 with CA
param set-default PCA9685_MIN1 1000
param set-default PCA9685_MAX1 2000
param set-default PCA9685_DIS1 1500
param set-default PCA9685_FAIL1 1500

param set-default PCA9685_FUNC2 101	# 201 - avoiding Control Allocator (Servo 1), 101 with CA
param set-default PCA9685_MIN2 1000
param set-default PCA9685_MAX2 2000
param set-default PCA9685_DIS2 1500
param set-default PCA9685_FAIL2 1500

# Cutter deck blades clutch, PCA9685 servo channel 3,  "RC FLAPS" (406) - leftmost switch, or "Servo 3" (203):
param set-default PCA9685_FUNC3 406
#param set-default PCA9685_FUNC3 203
param set-default PCA9685_MIN3 1000
param set-default PCA9685_DIS3 1000
param set-default PCA9685_FAIL3 1000

# Gas engine throttle, PCA9685 servo channel 4, "RC AUX1" (407) - left knob, or "Servo 4" (204):
#    - on minimum when disarmed or failed:
#param set-default PCA9685_FUNC4 407
param set-default PCA9685_FUNC4 204
param set-default PCA9685_MIN4 1000
param set-default PCA9685_DIS4 1000
param set-default PCA9685_FAIL4 1000

# Controlling PCA9685 servos 5,6,7,8 directly via "Servo 5..8" setting, by publishing actuator_servos.control[]:

# Strobes, PCA9685 servo channel 5, "Servo 5" (205) - flashing indicates Mission mode:
param set-default PCA9685_FUNC5 205
param set-default PCA9685_MIN5 1000
param set-default PCA9685_DIS5 1000
param set-default PCA9685_FAIL5 1000

# Horn, PCA9685 servo channel 6, "Servo 6" (206) - for alarms like GPS failure:
param set-default PCA9685_FUNC6 206
param set-default PCA9685_MIN6 1000
param set-default PCA9685_DIS6 1000
param set-default PCA9685_FAIL6 1000

# Spare PCA9685 servo channel 7 on "RC AUX2" (408) - right knob, or "Servo 7" (207):
param set-default PCA9685_FUNC7 408
#param set-default PCA9685_FUNC7 207
param set-default PCA9685_DIS7 1500

# Spare PCA9685 servo channel 8 - "Servo 8" (208):
param set-default PCA9685_FUNC8 208
param set-default PCA9685_DIS8 1500

# ======================================================================

# set R/C -> MAIN mappings:

# RC "mode 2" channels: ailerons: 1  pitch: 2  throttle: 3  rudder: 4
# We re-assign them to allow right stick control movement, left - functions like arming and flight mode:
param set-default RC_MAP_ROLL 1
param set-default RC_MAP_THROTTLE 2
param set-default RC_MAP_YAW 4
param set-default RC_MAP_PITCH 3

# set RC -> AUX mapping, names like "..FLAPS" to physical R/C channels:
#    5 and 6 are top middle pots. 7 (cutter) and 8 (kill) are top left switches. Top right switches not available.
param set-default RC_MAP_AUX1 5
param set-default RC_MAP_AUX2 6
param set-default RC_MAP_FLAPS 7

# left stick to the right ("rudder") - Arm, to the left - Disarm:
param set-default RC_MAP_ARM_SW 4
# we cannot have both arm switch and left stick gesture.
# to avoid "WARN  [commander] Arm stick gesture disabled if arm switch in use" warning:
param set-default MAN_ARM_GESTURE 0

# left stick all way up ("throttle") - Mission (3), down - Manual (0) modes:
param set-default RC_MAP_FLTMODE 3
param set-default COM_FLTMODE1 0
param set-default COM_FLTMODE6 3

# Kill switch - PWM off, after 0 seconds - disarm (also kills when transmitter off)
# that's the second upper switch from the left:
param set-default RC_MAP_KILL_SW 8

# This is to mimic successful calibration - it is normally set by QGroundControl:
param set-default RC_CHAN_CNT 6

param set-default RTL_CONE_ANG 0
param set-default RTL_MIN_DIST 1
param set-default RTL_DESCEND_ALT 3.0000
param set-default RTL_RETURN_ALT 3.0000


# for debugging, allow unsafe arming rules:
#param set-default COM_ARM_EKF_POS 1.0
#param set-default COM_RC_IN_MODE 1
#param set-default CBRK_IO_SAFETY 22027

# system_power not implemented
param set-default CBRK_SUPPLY_CHK 894281

#
# see src1/Firmware/build/emlid_navio2_default/platforms/posix/apps.cpp
#

# start BN-880 (UBLOX M8N) GPS. It was configured for 5Hz using u-center on Windows:
#gps start -d /dev/ttyUSB0 -b 115200 -p ubx
#gps start -d /dev/ttyS0 -b 115200 -p nmea

# start u-blox ZED-F9P - dual GPS for heading (originally at /dev/ttyACM1 ACM0):
# follow https://github.com/slgrobotics/robots_bringup/tree/main/Docs/Dragger to assign links:
gps start -d /dev/ttyGPS_MAIN -b 460800 -e /dev/ttyGPS_SEC -g 460800

# for lab debugging, use fake GPS (mid Florida location):
#fake_gps start

# start BN-880 GPS compass on I2C bus, address 0x1e:
#hmc5883 -X -R 0 start

# start PNI RM3100 compass on I2C address 0x23=35:
#rm3100 -X start

# start SeedStudio/Bosch BMI088 6-Axis IMU on external I2C bus:
#bmi088_i2c -A -R 0 -X -a 0x19 start
#bmi088_i2c -G -R 0 -X -a 0x69 start

# start IMU on SPI (/dev/spidev0.1):
mpu9250 -s -R 0 -M -f 20000 start
# same without magnitometer:
#mpu9250 -s -R 0 -f 20000 start

# start barometer emulation (AHRS must have baro input):
ms5611 -X start

# start MCP3008 based ADC on SPI (/dev/spidev0.0):
board_adc start

# start standard RGB LED on "external" I2C bus, default address 85:
rgbled -X start

# see Projects/tests/rc_receiver.py
# start modified version of RC reader
# (receiver connected to Teensy 3.2, RPi getting data over I2C, addr 72=0x48):
navio_sysfs_rc_in start

# ----------------------------------------
# commented out "start" commands below because they are already running, started by rcS, rc.rover_apps:

#rc_update start
#sensors start
#commander start
#navigator start

#
# Start the attitude and position estimator.
# already started by rc.rover_apps
#
#ekf2 start

# these two are obsoleted by ekf2 (see rc.rover_apps):
#attitude_estimator_q start
#local_position_estimator start

#
# Start position and attitude controllers.
# already started by rc.rover_apps
#
#rover_pos_control start
#rover_steering_control start

#
# Start Land Detector.
# already started by rc.rover_apps
#
#land_detector start rover
#
# ----------------------------------------

#
# Alternative estimators: Instead of EKF2, start the attitude and position estimator.
#
#ekf2 stop
#attitude_estimator_q start
#local_position_estimator start

# linux_pwm_out is deprecated, do not use.
set OUTPUT_MODE skip
echo "IP: starting pca9685_pwm_out start -a 0x40 -b 1"
pca9685_pwm_out start -a 0x40 -b 1

echo "OK: finished " $MYSCRIPTNAME
echo "====================================="
